### PR TITLE
Multiple files import

### PR DESCRIPTION
**Pull request by palmiak**
When we're importing multiple files and posts in those files have the same ID, only the first one is imported. This happens because WordPress Importer has a variable `processed_posts` which makes sure that no posts with the same ID are being imported.

But WP Importer imports only one file at the time. With WP-CLI it's quite possible that we want to import many files and that those posts will have the same IDs.

To fix this I changed only one thing - `processed_posts` is  cleared with every file being imported.

I've also added required tests.

ps. @schlessera thanks for helping me with this bug at WCLND.

### CODE REVIEW

**Comment by palmiak** [comment]
I gave it some thought and I see we have problem here - `processed_posts` is also used for connecting posts, menu and images. 

On one hand it's more a question of lesser evil and choosing what's more important:
- importing menus, images and posts from one blog, when they are exported as seperate files
- importing all posts from multiple sites into one

On the other hand I'm thinking about gathering processed posts into array indexed by slug from the site url. Thanks to this we could keep the processed post ID, but seperate them beetween multiple sites.

**Comment by schlessera** [comment]
What about indexing by filename?

**Comment by palmiak** [comment]
@schlessera I think that they should be grouped by the same index. The the test that is failing is related to menus and situation when you export posts and menus in separated files.

So, for example, if I have:
page-1-menu.xml
page-1-posts.xml
page-2-everything.xml
page-3-posts.xml
page-3-menu.xml

I should group them like this:
```php
$ids['page-1'];
$ids['page-2'];
$ids['page-3'];
```

I hope I'll be able to sit on it during the weekend.

**Comment by schlessera** [comment]
> Now I just see one problem - how to modify the test to simulate the fact that both export files have a different url? Can I use --url param in given WP install or maybe there is a better way.

Yes, using the `--url` param should be sufficient if it is passed all the way through.

In case you need more precise/extensive modifications to the internals for your test, you can always write arbitrary PHP into a file and require that file before running a command (See an example of this here: https://github.com/wp-cli/extension-command/blob/5a4bfac7890277a10c1048ee27f43c5de12b5b6d/features/plugin-install.feature#L88-L95).

**Comment by schlessera** [comment]
@palmiak Are you still up for working on this? Do you have a link to the PR you provided to WP Import?

**Comment by schlessera** [comment]
@palmiak As the import command was fixed by now via its release v0.7.0, we can look into getting this merged. I tried rebasing the PR, but I cannot push to the `spidersAgency` fork. Can you rebase this PR to see if we can make the tests pass?

**Comment by danielbachhuber** [comment]
Proceeding with https://github.com/wp-cli/wp-cli/issues/5594 for this repository. I've captured this PR to https://gist.github.com/danielbachhuber/e61e2bd34ab014a93c4ae9354e3f9041 in case this PR is auto-closed or broken in some way.

**Pull request closed without merging**
